# Set update schedule for GitHub Actions

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/"
    ignore:
      - dependency-name: "golang.org/x/tools"
      - dependency-name: "google.golang.org/grpc"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/tools"
    ignore:
      - dependency-name: "golang.org/x/tools"
      - dependency-name: "google.golang.org/grpc"
    schedule:
      interval: "daily"
